# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

install:
  - pip install coveralls
  - ./install_deps

script:
  - coverage run manage.py test --settings=core.settings.test_travis

after_success:
  - coveralls
