#!/bin/bash
set -eu

# run isort diff
isort -rc accounts core dashboard services --diff

# ask dev if they want isort to apply changes
read -r -p "Apply changes? (Default: No) y/N: " apply_changes

if [[ ! "$apply_changes" ]]; then
    apply_changes='N'
fi

if [[ "$apply_changes" != 'N' ]]; then
    isort -rc accounts core dashboard services
    echo "I have exerciiiiiiiised the deeeemons, this code... is clear. https://www.youtube.com/watch?v=xMUKPUjxmF4 🍺"
fi
